GET localhost:8080/api/companies/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTcwNjQ3Mjk4NCwiZXhwIjoxNzA2NTU5Mzg0fQ.39cRpYUEGKzagvm64FcCj0u9eKOmbD94S5EPHjEfCKTZj6H6iH6KRjc2FBVedyrRHdtwLYrEwlOfM_uF16Uihw