GET localhost:8080/api/companies/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTcwNjQyMzMyNSwiZXhwIjoxNzA2NTA5NzI1fQ.kOH8mV6ORfOthg31C_5P8ej3tBrbAcnbodr8jnz9vHecrc4h-nhH-mR8_wjadaq1aR9cuA3rad6wp7FQp91UZw