GET localhost:8080/api/schools/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTcwNjc1NDUxMSwiZXhwIjoxNzA2ODQwOTExfQ.UVhHadPeJ9fAlqSfS_4KjiAFu26H1nyQPz1vhtEna_h8D2JikHJpYLsnJB4Ko2H6z47L_2Vdgg5nYh0aj8qERw

