POST localhost:8080/api/register/
Content-Type: application/json

{
  "username": "admin",
  "password": "password",
  "role": "ADMIN"
}

###
POST localhost:8080/api/students/add/
Content-Type: application/json
